package io.github.aedev.flow.ui.screens.player

import io.github.aedev.flow.data.model.Video
import io.github.aedev.flow.player.state.AudioTrackOption
import io.github.aedev.flow.player.state.EnhancedPlayerState
import io.github.aedev.flow.player.state.QualityOption
import io.github.aedev.flow.player.state.SubtitleOption
import io.github.aedev.flow.ui.screens.player.state.VideoPlayerUiState

internal fun fakeVideo(
    id: String = "video-1",
    title: String = "Fixture video",
    channelName: String = "Fixture channel",
    channelId: String = "channel-1",
): Video =
    Video(
        id = id,
        title = title,
        channelName = channelName,
        channelId = channelId,
        thumbnailUrl = "",
        duration = 125,
        viewCount = 1_000L,
        uploadDate = "2026-01-01",
    )

internal val FIXTURE_QUALITY_AUTO = QualityOption(height = 0, label = "Auto", bitrate = 0L)
internal val FIXTURE_QUALITY_1080 =
    QualityOption(height = 1080, label = "1080p", bitrate = 5_000_000L, codecKey = "vp9", streamKey = "1080_vp9")
internal val FIXTURE_QUALITY_720 =
    QualityOption(height = 720, label = "720p", bitrate = 2_500_000L, codecKey = "h264", streamKey = "720_h264")

internal val FIXTURE_AUDIO_TRACKS =
    listOf(
        AudioTrackOption(index = 0, label = "English", language = "en", bitrate = 128_000L),
        AudioTrackOption(index = 1, label = "Deutsch", language = "de", bitrate = 128_000L),
    )

internal val FIXTURE_SUBTITLES =
    listOf(
        SubtitleOption(url = "https://example.invalid/en.vtt", language = "en", label = "English", isAutoGenerated = false),
    )

internal fun fakePlayerState(
    isPlaying: Boolean = false,
    isLive: Boolean = false,
    currentQuality: Int = 1080,
    effectiveQuality: Int = 1080,
    playbackSpeed: Float = 1.0f,
    availableQualities: List<QualityOption> = listOf(FIXTURE_QUALITY_AUTO, FIXTURE_QUALITY_1080, FIXTURE_QUALITY_720),
    availableAudioTracks: List<AudioTrackOption> = FIXTURE_AUDIO_TRACKS,
    availableSubtitles: List<SubtitleOption> = FIXTURE_SUBTITLES,
): EnhancedPlayerState =
    EnhancedPlayerState(
        currentVideoId = "video-1",
        isPlaying = isPlaying,
        isPrepared = true,
        currentQuality = currentQuality,
        effectiveQuality = effectiveQuality,
        currentQualityKey = FIXTURE_QUALITY_1080.streamKey,
        availableQualities = availableQualities,
        availableAudioTracks = availableAudioTracks,
        availableSubtitles = availableSubtitles,
        playbackSpeed = playbackSpeed,
        isLive = isLive,
    )

internal fun fakeUiState(
    video: Video = fakeVideo(),
    relatedVideos: List<Video> = emptyList(),
    isLiveChatAvailable: Boolean = false,
): VideoPlayerUiState =
    VideoPlayerUiState(
        cachedVideo = video,
        relatedVideos = relatedVideos,
        isLiveChatAvailable = isLiveChatAvailable,
    )

/** The related lane's source, as the player collaborators receive it. */
internal interface RelatedFetcher {
    suspend fun getRelatedCandidates(videoId: String): List<Video>
}
