// Caption tracks from a player response, ported from the app's CaptionTrackResolver: every authored
// and auto-generated track, plus one machine translation into the listener's caption language when
// the video has no track in it. Tracks are served as WebVTT, the one form the contract names.
import type { CaptionTrack } from '@milkbeat/plugin-sdk';
import { type Json, text } from '../util';

export const TRANSLATED_PARAM = 'tlang';
const NO_PREFERENCE = 'none';

const baseLanguage = (tag: string): string => tag.split('-')[0].split('_')[0].toLowerCase();

/** [baseUrl] asking for [fmt], without any earlier fmt or translation parameter. */
export function timedTextUrl(baseUrl: string, fmt = 'vtt'): string {
  const absolute = baseUrl.startsWith('/') ? `https://www.youtube.com${baseUrl}` : baseUrl;
  const index = absolute.indexOf('?');
  const path = index < 0 ? absolute : absolute.slice(0, index);
  const query = index < 0 ? '' : absolute.slice(index + 1);
  const isParam = (part: string, name: string) => part.toLowerCase() === name || part.toLowerCase().startsWith(`${name}=`);
  const kept = query.split('&').filter((part) => part && !isParam(part, 'fmt') && !isParam(part, TRANSLATED_PARAM));
  kept.push(`fmt=${fmt}`);
  return `${path}?${kept.join('&')}`;
}

/** The best track in [languageTag]: same base language, the exact tag first, then authored over ASR. */
export function bestMatch<T>(candidates: T[], languageTag: string | null | undefined, tagOf: (item: T) => string, isAuto: (item: T) => boolean): T | undefined {
  if (!languageTag || languageTag === NO_PREFERENCE) return undefined;
  const wanted = baseLanguage(languageTag);
  return candidates
    .filter((item) => baseLanguage(tagOf(item)) === wanted)
    .sort(
      (a, b) =>
        Number(tagOf(a).toLowerCase() !== languageTag.toLowerCase()) - Number(tagOf(b).toLowerCase() !== languageTag.toLowerCase()) ||
        Number(isAuto(a)) - Number(isAuto(b)),
    )[0];
}

export function resolveCaptions(playerResponse: Json, translateTo?: string | null): CaptionTrack[] {
  const renderer = playerResponse?.captions?.playerCaptionsTracklistRenderer;
  const raw: Json[] = Array.isArray(renderer?.captionTracks) ? renderer.captionTracks : [];
  const tracks = raw.filter((track) => track?.baseUrl && track?.languageCode);
  if (!tracks.length) return [];

  const resolved: CaptionTrack[] = tracks.map((track) => ({
    url: timedTextUrl(track.baseUrl),
    language: track.languageCode,
    name: text(track.name) || track.languageCode,
    autoGenerated: track.kind === 'asr',
    translated: false,
    mimeType: 'text/vtt',
  }));

  const wanted = translateTo && translateTo !== NO_PREFERENCE ? translateTo : undefined;
  if (!wanted) return resolved;
  const languages: Json[] = Array.isArray(renderer?.translationLanguages) ? renderer.translationLanguages : [];
  const offered = languages.find((language) => language?.languageCode && baseLanguage(language.languageCode) === baseLanguage(wanted));
  if (!offered) return resolved;
  const covered = bestMatch(resolved, offered.languageCode, (track) => track.language, (track) => !!track.autoGenerated);
  if (covered) return resolved;
  // An authored source translates better than speech recognition.
  const source = tracks.find((track) => track.isTranslatable && track.kind !== 'asr') ?? tracks.find((track) => track.isTranslatable);
  if (!source) return resolved;
  return [
    ...resolved,
    {
      url: `${timedTextUrl(source.baseUrl)}&${TRANSLATED_PARAM}=${encodeURIComponent(offered.languageCode)}`,
      language: offered.languageCode,
      name: text(offered.languageName) || offered.languageCode,
      autoGenerated: true,
      translated: true,
      mimeType: 'text/vtt',
    },
  ];
}
