package io.github.aedev.flow.player.stream

import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.util.Locale

object CaptionTrackResolver {
    /** Marks a track produced by YouTube's machine translation of another caption track. */
    const val TRANSLATED_PARAM = "tlang"

    const val NO_PREFERRED_LANGUAGE = "none"

    fun isTranslated(stream: SubtitlesStream): Boolean = stream.getContent().contains("&$TRANSLATED_PARAM=")

    fun <T> bestMatch(
        candidates: List<T>,
        languageTag: String?,
        tagOf: (T) -> String?,
        isAutoGenerated: (T) -> Boolean,
    ): T? {
        val wanted = languageTag?.takeIf { it.isNotBlank() && it != NO_PREFERRED_LANGUAGE } ?: return null
        val wantedBase = baseLanguage(wanted)
        val ranked =
            candidates
                .filter { baseLanguage(tagOf(it).orEmpty()) == wantedBase }
                .sortedWith(
                    compareBy<T> { !tagOf(it).equals(wanted, ignoreCase = true) }
                        .thenBy { isAutoGenerated(it) },
                )
        return ranked.firstOrNull()
    }

    private fun baseLanguage(tag: String): String =
        tag
            .substringBefore('-')
            .substringBefore('_')
            .lowercase(Locale.ROOT)
}
