package io.github.aedev.flow.player.stream

import io.github.aedev.flow.player.state.SubtitleOption
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/** A signed timedtext URL as YouTube serves it today — note the trailing `fmt=srv3`. */
private const val BASE_URL =
    "https://www.youtube.com/api/timedtext?v=abc&ei=XYZ&caps=asr&sparams=ip,ipbits,expire,v" +
        "&signature=DEADBEEF.0123&key=yt8&lang=en&fmt=srv3"

class CaptionTrackResolverTest {
    @Test
    fun `a stored region tag still matches the base language and prefers the human track`() {
        val options =
            listOf(
                SubtitleOption(url = "a", language = "pt-BR", label = "Portuguese", isAutoGenerated = true),
                SubtitleOption(url = "b", language = "pt-BR", label = "Portuguese", isAutoGenerated = false),
                SubtitleOption(url = "c", language = "en", label = "English", isAutoGenerated = false),
            )

        val match =
            CaptionTrackResolver.bestMatch(
                candidates = options,
                languageTag = "pt",
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated },
            )

        assertEquals("b", match?.url)
    }

    @Test
    fun `no preference matches nothing`() {
        val options = listOf(SubtitleOption(url = "a", language = "en", label = "English", isAutoGenerated = false))

        assertNull(
            CaptionTrackResolver.bestMatch(
                candidates = options,
                languageTag = CaptionTrackResolver.NO_PREFERRED_LANGUAGE,
                tagOf = { it.language },
                isAutoGenerated = { it.isAutoGenerated },
            ),
        )
    }
}

class CaptionTrackAutoTranslationTest
