package nl.neerdael.milkbeat.plugin

import kotlinx.serialization.Serializable
import nl.neerdael.milkbeat.catalog.Artwork
import nl.neerdael.milkbeat.catalog.EntityRef
import nl.neerdael.milkbeat.catalog.TrackDescriptor

/**
 * A track to resolve for listening. The host asks for the picture too ([video]) only when the
 * listener shows music videos; [maxVideoHeight] and [videoCodecs] describe what this TV decodes.
 */
@Serializable
data class ResolveAudioRequest(
    val track: TrackDescriptor,
    val quality: AudioQuality = AudioQuality.AUTO,
    val video: Boolean = false,
    val maxVideoHeight: Int? = null,
    val videoCodecs: List<String> = emptyList(),
    val language: String? = null,
    /** The previous stream failed (e.g. HTTP 403); the plugin should not hand back the same one. */
    val retry: Boolean = false,
)

@Serializable
enum class AudioQuality {
    AUTO,
    HIGH,
    MEDIUM,
    LOW,
}

/**
 * Where the host fetches a track's sound, and optionally its picture. The URL must accept HTTP range
 * requests; the host reads it in chunks and asks again when [expiresAtMs] passes. [cacheKey] names
 * the bytes across URL refreshes, so cached audio stays valid.
 */
@Serializable
data class AudioStream(
    val url: String,
    val cacheKey: String,
    val mimeType: String,
    val codecs: String? = null,
    val bitrate: Int? = null,
    val contentLength: Long? = null,
    val headers: Map<String, String> = emptyMap(),
    val expiresAtMs: Long? = null,
    /** Integrated loudness relative to the provider's reference, for volume normalisation. */
    val loudnessDb: Double? = null,
    /** Opaque; handed back with [ReportPlaybackRequest] so the plugin can report the listen. */
    val trackingToken: String? = null,
    val video: MediaFormat? = null,
)

/** A played-enough listen or view, reported to the provider's history when the listener allows it. */
@Serializable
data class ReportPlaybackRequest(
    val entity: EntityRef,
    val trackingToken: String? = null,
    val playedMs: Long,
    val durationMs: Long? = null,
)

/** A video to play in the video player. */
@Serializable
data class ResolveVideoRequest(
    val entity: EntityRef,
    val maxHeight: Int? = null,
    val codecs: List<String> = emptyList(),
    val language: String? = null,
    val retry: Boolean = false,
)

@Serializable
enum class VideoKind {
    VOD,
    LIVE,

    /** Scheduled; [VideoPlayback.startsAtMs] says when. */
    UPCOMING,
}

/**
 * Everything the video player needs: the formats to merge into one picture and one sound, or the
 * live manifests, plus captions, chapters and segments listeners may skip.
 */
@Serializable
data class VideoPlayback(
    val kind: VideoKind,
    val details: VideoDetails,
    val formats: List<MediaFormat> = emptyList(),
    val hlsUrl: String? = null,
    val dashUrl: String? = null,
    val captions: List<CaptionTrack> = emptyList(),
    val chapters: List<Chapter> = emptyList(),
    val skipSegments: List<SkipSegment> = emptyList(),
    val headers: Map<String, String> = emptyMap(),
    val expiresAtMs: Long? = null,
    val startsAtMs: Long? = null,
    val trackingToken: String? = null,
)

@Serializable
data class VideoDetails(
    val entity: EntityRef,
    val title: String,
    val channelName: String? = null,
    val channel: EntityRef? = null,
    val channelAvatar: Artwork? = null,
    val durationSeconds: Int? = null,
    val description: String? = null,
    val viewsLabel: String? = null,
    val publishedLabel: String? = null,
    val artwork: Artwork? = null,
    val keywords: List<String> = emptyList(),
)

@Serializable
enum class FormatType {
    AUDIO,
    VIDEO,
}

/** One downloadable rendition. The host plays a video format and an audio format side by side. */
@Serializable
data class MediaFormat(
    val id: String,
    val type: FormatType,
    val url: String,
    val mimeType: String,
    val codecs: String? = null,
    val width: Int? = null,
    val height: Int? = null,
    val fps: Int? = null,
    val bitrate: Int? = null,
    val averageBitrate: Int? = null,
    val contentLength: Long? = null,
    val durationMs: Long? = null,
    val initRange: ByteRange? = null,
    val indexRange: ByteRange? = null,
    val qualityLabel: String? = null,
    val hdr: Boolean = false,
    val audioTrack: AudioTrackInfo? = null,
)

@Serializable
data class ByteRange(
    val start: Long,
    val end: Long,
)

@Serializable
data class AudioTrackInfo(
    val id: String,
    val name: String? = null,
    val language: String? = null,
    val original: Boolean = false,
    /** Dynamic range compressed, for quiet listening. */
    val drc: Boolean = false,
)

@Serializable
data class CaptionTrack(
    val url: String,
    val language: String,
    val name: String,
    val autoGenerated: Boolean = false,
    val mimeType: String = "text/vtt",
)

@Serializable
data class Chapter(
    val title: String,
    val startMs: Long,
)

/** A stretch listeners may skip, such as a sponsor read; [category] is shown on the skip button. */
@Serializable
data class SkipSegment(
    val startMs: Long,
    val endMs: Long,
    val category: String,
)
